#!/usr/bin/env bash
# Pre-push gate. Mirrors the steps the Release workflow runs in CI so failures
# show up locally instead of breaking the deploy. Build must run BEFORE
# typecheck/test — downstream workspace packages import from @released/core
# whose .d.ts files are only generated by the build.
#
# Skip with `git push --no-verify` when intentionally pushing WIP.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "→ build"
pnpm -r build

echo "→ typecheck"
pnpm -r typecheck

echo "→ test"
pnpm -r test
