#!/usr/bin/env bash
# Pre-push gate. Mirrors the steps both workflows run in CI (.github/
# workflows/{ci,release}.yml) so failures show up locally instead of
# breaking the deploy. Build must run BEFORE typecheck/test — downstream
# workspace packages import from @released/core whose .d.ts files are
# only generated by the build.
#
# Lint runs LAST: build/typecheck/test tell you whether the code is
# broken; lint is a fast nag layer for style and a11y. Putting it last
# means a broken build doesn't hide behind lint noise.
#
# Skip with `git push --no-verify` when intentionally pushing WIP.
set -euo pipefail

# Skip in CI — the workflow already runs build/typecheck/test/lint as
# explicit steps, and the Changesets action's force-push to
# changeset-release/main triggers this via the pre-push hook,
# duplicating work and risking environmental mismatches.
if [ -n "${CI:-}" ]; then
  exit 0
fi

cd "$(git rev-parse --show-toplevel)"

echo "→ build"
pnpm -r build

echo "→ typecheck"
pnpm -r typecheck

echo "→ test"
pnpm -r test

echo "→ lint"
pnpm lint

# publint: structural lint of the published CLI package. npm-provided (every
# clone has it after pnpm install), so it hard-fails like the checks above.
echo "→ publint"
pnpm exec publint ./packages/cli

# osv: dependency CVE scan. LOCAL is warn-only (|| true) — a contributor may not
# have osv-scanner installed (esp. Windows), and CI runs the same script as the
# authoritative High/Critical gate on every PR. The agent still sees findings
# here for early warning; the push is never blocked locally.
echo "→ osv (local heads-up; CI gates High/Critical on PRs)"
scripts/osv-check.sh || true

# Marker for Claude Code's .claude/hooks/{commit-gate,validate-gate}.sh —
# its presence (+ mtime newer than any .ts/.tsx edited this session) lets
# Claude `git commit`/`git push` and declare turns done. See those hooks
# for the freshness logic.
touch /tmp/released-validate.stamp
