#!/usr/bin/env bash
# Pre-push gate. Mirrors the steps both workflows run in CI (.github/
# workflows/{ci,release}.yml) so failures show up locally instead of
# breaking the deploy. Build must run BEFORE typecheck/test — downstream
# workspace packages import from @released/core whose .d.ts files are
# only generated by the build.
#
# Lint runs LAST: build/typecheck/test tell you whether the code is
# broken; lint is a fast nag layer for style and a11y. Putting it last
# means a broken build doesn't hide behind lint noise.
#
# Skip with `git push --no-verify` when intentionally pushing WIP.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "→ build"
pnpm -r build

echo "→ typecheck"
pnpm -r typecheck

echo "→ test"
pnpm -r test

echo "→ lint"
pnpm lint
